services:
  - type: web
    name: afh-backend
    env: node
    rootDir: BackEnd_AFH-main
    buildCommand: "npm install"
    startCommand: "node app.js"
    plan: free
    envVars:
      - key: DB_URI
        sync: false
      - key: PORT
        sync: false
      - key: TOKEN_KEY
        sync: false
      - key: TOKEN_EXPIRATION
        sync: false
      - key: EMAIL
        sync: false
      - key: PASSWORD
        sync: false
